import Head from "next/head";
import React, { useContext } from "react";
import AuthContext from "@/store/auth-context";

export default function Home() {
  const authCtx = useContext(AuthContext);

  return (
    <React.Fragment>
      <Head>
        <title>Habittus App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home page</h1>
    </React.Fragment>
  );
}
